version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - inventory-api
      - product-service

  inventory-api:
    build: ./inventory-api
    ports:
      - "5000:5000"
    restart: always

  product-service:
    build: ./product-service
    ports:
      - "6100:6000"
    restart: always
